# -*- coding: utf-8 -*-
"""DATA ENGINEERING.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1I548RasnKsvdgMZBvgmm5UwEIXKPBaWc
"""

import pandas as pd

df=pd.read_csv("student_performance.csv")

df.head()

df.tail()

print(df.shape)
print(df.shape[0])#rows
print(df.shape[1])#columns

print(df.dtypes)#data types

df.describe()

print(df.isnull().sum())

print(df['age'])

print(df['department'].unique())

print(df['department'].value_counts())

cs_students=df[df['department']=='Computer Science']
print(len(cs_students))

high_attendence=df[df['attendance_percentage']>90]
print(len(high_attendence))
print(high_attendence)

df['total_score']=df['math_score']+df['science_score']+df['programming_score']+df['english_score']

top_student=df.loc[df['total_score'].idxmax()]

print("Top student : ")
print(f"Name : {top_student['name']}")
print(f"Department : {top_student['department']}")
print(f"Total Score : {top_student['total_score']}")
print(f"Attendance : {top_student['attendance_percentage']}")

dept_avg=df.groupby('department')['total_score'].mean().round(2)
print("Avg total score by department:")
print(dept_avg)

df_sorted=df.sort_values(by='total_score',ascending=False)
print(df_sorted.head(10))



"""Question
1. How many students are from electronic department?
2. What is the averaage attendance of the female students?
3. who is the student with the lowest programming score?
4. how many students score above 80 in math?
5. What is the average total score for students with attendance above 90 percentage?
"""

#How many students are from electronic department?
electronic_students=df[df['department']=='Electronics']
print(len(electronic_students))

#What is the averaage attendance of the female students?
female_students=df[df['gender']=='Female']
avg_attendance=female_students['attendance_percentage'].mean()
print(avg_attendance)

#who is the student with the lowest programming score?
lowest=df[df['programming_score']==df['programming_score'].min()]
print(lowest['name'])

#how many students score above 80 in math?
maths=df[df['math_score']>80]
print(len(maths))

#What is the average total score for students with attendance above 90 percentage?
above90=df[df['attendance_percentage']>90]
avg_above90=above90['total_score'].mean()
print(avg_above90)



"""# MINI PROJECT : Student Data Explorer
# Objective:

Create a Student Performance Explorer using Pandas and Pythin to analyze student data and generate a detailed report.

# Dataset Columns:

name

gender

department

math_score

programming_score

attendance_percentage

total_score

# Tasks to perform:
1. Display Project title

 Print a formatte title with seperator lines

2. Dataset Overview

Display:

-Total number of students

-total number of columns

-number of unique departments

3. Department wise analysis

display the count of students in each department.

4. Score Analysis

Find and Display:

-highest math score

-lowest math score

-avg math score

-avg programming score

-avg attendance percentage

5. Gender wise Analysis

Calculate and display avg total score by gender

6. Top performers

Display top 5 students based on total score.

Show:

-Student name

-Department

-total score

7. Attendance Analysis

Find students whose attendance is below 75%

Display:

-Name

-Department

-Atendance Percentage

If all students have attendance above 75%, print a suitable message.

# Concepts to use:

-pandas, DataFrame, groupby(), value_counts(), mean(), max(), min(), sort_values(), iterrows(), Conditional Statements, f-strings
"""

print("="*40)
print("Student Performance Explorer")
print("="*40)
print()
print("-"*40)
print("Dataset Overview")
print("-"*40)
print("Total number of students=",len(df))
print("Total number of columns=",df.shape[1])
print("Number of unique departments=",df['department'].nunique())
print()
print("-"*40)
print("Department wise analysis")
print("-"*40)
print(df['department'].value_counts())
print()
print("-"*40)
print("Score Analysis")
print("-"*40)
print("highest math score=",df['math_score'].max())
print("lowest math score=",df['math_score'].min())
print("avg math score=",df['math_score'].mean())
print("avg programming score=",df['programming_score'].mean())
print("avg attendance percentage=",df['attendance_percentage'].mean())
print()
print("-"*40)
print("Gender wise Analysis")
print("-"*40)
female_students=df[df['gender']=='Female']
male_students=df[df['gender']=='Male']
print("avg total score of female students=",female_students['total_score'].mean())
print("avg total score of male students=",male_students['total_score'].mean())
print()
print("-"*40)
print("Top performers")
print("-"*40)
df_sorted=df.sort_values(by='total_score',ascending=False)
top=df_sorted.head(5)
print(top[['name','department','total_score']])
print()
print("-"*40)
print("Attendance Analysis")
print("-"*40)
below_75=df[df['attendance_percentage']<75]
if len(below_75)==0:
    print("All students have attendance above 75%")
else:
    print(below_75[['name','department','attendance_percentage']])

