# -*- coding: utf-8 -*-
"""Day4_ml_pyspark_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SS5GL_ljK4UZHL7y8_93BGhGA8Cj7cBD
"""

import pandas as pd
df=pd.read_csv("SOCR-HeightWeight.csv")
df.shape

df.isnull().sum()

from sklearn.model_selection import train_test_split

x=df[['Height(Inches)']]
y=df[['Weight(Pounds)']]
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

x_train

from sklearn.linear_model import LinearRegression
model=LinearRegression()
model.fit(x_train,y_train)

y_pred=model.predict(x_test)

from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score

mean_absolute_error(y_test,y_pred)

mean_squared_error(y_test,y_pred)

r2_score(y_test,y_pred)

import joblib

joblib.dump(model,"linear.pk1")