# -*- coding: utf-8 -*-
"""Day4_ml_pyspark_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tSsXKsDcpdu8Q6_8f6f8VeDjGhsP75Q-
"""

import joblib

a=joblib.load("linear.pk1")
a.predict([[80]])

pip install pyspark --quiet

from pyspark.sql import SparkSession
from pyspark.sql import functions as F

from pyspark.sql.functions import year,month,to_date,col,round as spark_round


import matplotlib.pyplot as plt
import pandas as pd
import warnings
warnings.filterwarnings("ignore")

spark=SparkSession.builder \
    .appName('Day4_BigData_sales')\
    .config('spark.sql.adaptive','true') \
    .getOrCreate()

print(f"Spark version: {spark.version}")
print(f"SparkSession: Active")
print(f"Application: {spark.sparkContext.appName}")

df_bronze= spark.read \
  .option('header','true') \
  .option('inferSchema','true')\
  .csv('large_sales_data.csv')
print("===Bronze layer - raw data")
print(f"rows :{df_bronze.count()}")
print(f"columns :{len(df_bronze.columns)}")

print("First five rows")
df_bronze.show(5,truncate=False)
print("basic statistics for numeric columns:")
df_bronze.select('quantity','unit_price','revenue').describe().show()

df_bronze.write \
    .mode('overwrite')\
    .parquet('sales_bronze.parequet')
print("bronze Parquetsaced successfully")

a=pd.read_csv("data.csv")
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
x=a[['bedrooms','sqft_living','yr_built']]
y=a[['price']]
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)
model=LinearRegression()
model.fit(x_train,y_train)
y_predict=model.predict(x_test)
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score
print(mean_absolute_error(y_test,y_predict))
print(mean_squared_error(y_test,y_predict))
r2_score(y_test,y_predict)
import joblib
joblib.dump(model,"linear2.pkl")
b=joblib.load("linear2.pkl")
b.predict([[3,1500,1998]])