# -*- coding: utf-8 -*-
"""day5_ml_pyspark.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fwI_f-gMuroHMTb1w_bIg5vdt0tNWWqD
"""

import pandas as pd
df=pd.read_csv('data.csv')
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score
x=df[['bedrooms','sqft_living','yr_built']]
y=df[['price']]
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)
from sklearn.tree import DecisionTreeRegressor
dt_model=DecisionTreeRegressor(
    max_depth=5,
    random_state=42
)
dt_model.fit(x_train,y_train)
y_predict=dt_model.predict(x_test)
print("Decision tree mean absolute error:",mean_absolute_error(y_test,y_predict))
print("Decision tree mean squared error:",mean_squared_error(y_test,y_predict))
print("Decision tree r2 score error:",r2_score(y_test,y_predict))

import pandas as pd
df1=pd.read_csv('data.csv')
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score
x=df1[['bedrooms','sqft_living','yr_built']]
y=df1[['price']]
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)
from sklearn.ensemble import RandomForestRegressor
rf_model=RandomForestRegressor(
    n_estimators=100,

    random_state=42
)
rf_model.fit(x_train,y_train)
y_predict=rf_model.predict(x_test)
print("Random forest mean absolute error:",mean_absolute_error(y_test,y_predict))
print("Random forest mean squared error:",mean_squared_error(y_test,y_predict))
print("Random r2 score error:",r2_score(y_test,y_predict))